events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 80;
        root /usr/share/nginx/html;

        location = /visitor-count {
            proxy_pass http://127.0.0.1:9992;
            proxy_set_header Host $host;
            add_header Cache-Control no-store;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
