import logging
import os
from abc import ABC, abstractmethod
from enum import IntEnum
from dataclasses import dataclass, field
from typing import Optional, Dict, Tuple, Type
from protosuites.proto_info import IProtoInfo
from var.settings import DEFAULT_ROOT_PATH


class TestType(IntEnum):
    """Enumeration of supported test measurement types."""
    throughput = 0
    latency = 1
    jitter = 2
    rtt = 3
    sshping = 4
    scp = 5


# add mapping for the test type
test_type_str_mapping = {
    TestType.throughput: "iperf3",
    TestType.latency: "latency",
    TestType.jitter: "jitter",
    TestType.rtt: "rtt",
    TestType.sshping: "sshping",
    TestType.scp: "scp"
}

# ---------------------------------------------------------------------------
# Proxy-style protocols: traffic enters the tunnel on the **client** side.
# All other tunnel / direct protocols: traffic reaches the **server** side.
# ---------------------------------------------------------------------------
PROXY_PROTOCOLS = frozenset({"KCP", "QUIC"})


@dataclass
class TestConfig:
    """Configuration shared by every ``ITestSuite`` implementation.

    Fields cover the union of parameters needed by all current test tools.
    Each tool uses the subset that is relevant to it — see the per-tool
    ``from_tool_dict()`` class methods for the authoritative mapping from
    YAML keys to ``TestConfig`` fields.

    Attributes:
        name:         Name of the test tool binary (e.g. ``iperf3``, ``ping``).
        test_name:    Logical name of the test case (from the YAML key).
        interval:     Reporting / sampling interval in seconds.
        interval_num: Number of reporting intervals.
        parallel:     Number of parallel streams (iperf only).
        packet_size:  Payload size in bytes (rtt only).
        packet_count: Number of packets per iteration (rtt only).
        packet_type:  ``tcp`` or ``udp`` (iperf only).
        file_size:    Transfer size in MB (scp only).
        bitrate:      Target bitrate in Mbit/s; 0 = unlimited (iperf only).
        test_type:    The :class:`TestType` that selects the analyzer.
        client_host:  Host index that acts as the traffic sender.
        server_host:  Host index that acts as the traffic receiver.
        allow_fail:   When *True* a failure does not abort the run.
        args:         Free-form extra arguments forwarded to the tool.
        root_path:    Filesystem root for result artefacts.
    """
    name: str = field(default="")  # name of test tool
    test_name: str = field(default="")  # name of test
    interval: Optional[float] = field(default=1.0)
    interval_num: Optional[int] = field(default=10)
    parallel: Optional[int] = field(default=1)  # Number of parallel streams
    packet_size: Optional[int] = field(default=1024)
    packet_count: Optional[int] = field(default=10)
    packet_type: Optional[str] = field(default="tcp")  # udp or tcp
    file_size: Optional[int] = field(default=1)  # for scp, default 1 MB
    bitrate: Optional[int] = field(default=0)
    # target bitrate in #[KMG][/sec (0 for unlimited)(default 1 Mbit/sec for UDP, unlimited for TCP)
    test_type: Optional[TestType] = field(default=TestType.throughput)
    client_host: Optional[int] = field(default=None)
    server_host: Optional[int] = field(default=None)
    allow_fail: Optional[bool] = field(default=False)
    args: Optional[str] = field(default="")  # args for test tool
    root_path: str = field(default=DEFAULT_ROOT_PATH)


@dataclass
class TestResult:
    """
    TestResult is a dataclass that holds the result of the test.
    is_success: A boolean value that indicates whether the test was successful.
    record: The record file generated by the test which contains the test results.
        file name pattern: <class_name>_<test_type>_<client_host>_<server_host>.log
    """
    is_success: bool = field(default=False)
    pattern: str = field(default="")
    record: str = field(default="")  # log file
    result_dir: str = field(default="")
    is_competition_test: bool = field(default=False)


class ITestSuite(ABC):
    """Base class for all test-suite implementations.

    Subclasses must implement:

    * :meth:`pre_process` — one-time setup before the measurement runs.
    * :meth:`_run_test` — core measurement logic.
    * :meth:`post_process` — cleanup / result rewriting after the measurement.

    The concrete :meth:`run` method orchestrates the lifecycle:
    ``pre_process → validate → _run_test → post_process``.

    **Helper methods available to subclasses:**

    * :meth:`resolve_receiver` — protocol-aware receiver IP + port resolution.
    * :meth:`_default_client_server` — fills in default client/server host
      indices when the YAML config does not specify them.

    **Extension contract — adding a new test tool:**

    1. Create ``src/testsuites/test_<tool>.py``.
    2. Subclass :class:`ITestSuite`.
    3. Register via the ``@register_test_suite`` decorator (see below).
    4. Implement ``from_tool_dict()`` to own YAML-to-TestConfig mapping.
    5. Implement ``_run_test()`` using ``resolve_receiver()`` for IP/port.
    """

    def __init__(self, config: TestConfig) -> None:
        self.base_name = ""
        self.config = config
        root_path = self.config.root_path
        self.result_dir = f"{root_path}test_results/{self.config.test_name}/"
        if not os.path.exists(f"{self.result_dir}"):
            os.makedirs(f"{self.result_dir}")
        if self.config.test_type is not None:
            self.result = TestResult(
                False, pattern=f"{self.__class__.__name__}_{self.config.name}_{self.config.packet_type}"
                f"_{test_type_str_mapping[self.config.test_type]}"
                f"_h{self.config.client_host}_h{self.config.server_host}.log",
                record="", result_dir=self.result_dir)
        else:
            logging.error("Test type is not set. %s", self.config.test_type)
            self.result = TestResult(False, pattern="", record="")

    # ------------------------------------------------------------------
    # Public helpers shared by all subclasses
    # ------------------------------------------------------------------

    def name(self) -> str:
        return self.config.name

    @abstractmethod
    def post_process(self) -> bool:
        pass

    @abstractmethod
    def pre_process(self) -> bool:
        pass

    @abstractmethod
    def _run_test(self, network: 'INetwork', proto_info: IProtoInfo) -> bool:  # type: ignore
        pass

    def run(self, network: 'INetwork', proto_info: IProtoInfo) -> TestResult:  # type: ignore
        if self.result.pattern == "":
            return self.result
        if proto_info.get_protocol_version() != "" and proto_info.get_protocol_version() != 'latest':
            if 'tcp' not in proto_info.get_protocol_name():
                self.base_name = proto_info.get_protocol_name().upper() + "-" + \
                    proto_info.get_protocol_version()
            else:
                self.base_name = proto_info.get_protocol_name().upper()
        else:
            self.base_name = proto_info.get_protocol_name().upper()
        self.result.record = self.result.result_dir + \
            self.base_name + "_" + self.result.pattern
        self.result.is_success = self.pre_process()
        # checking for non-distributed protocols
        if not proto_info.is_distributed():
            if self.config.client_host is None:
                logging.error(
                    "Test non-distributed protocols without client host is not supported.")
                return self.result
            if self.config.server_host is None:
                logging.error(
                    "Test non-distributed protocols without server host is not supported.")
                return self.result
        if not self.result.is_success:
            return self.result
        if not self.__validate_host_config(network):
            self.result.is_success = False
            return self.result
        self.result.is_success = self._run_test(network, proto_info)
        if not self.result.is_success:
            logging.error("ITestSuite %s failed.", self.config.test_name)
            return self.result
        self.result.is_success = self.post_process()
        if not self.result.is_success:
            return self.result
        return self.result

    def is_competition_test(self) -> bool:
        return False

    def is_succeed(self) -> bool:
        return self.result.is_success

    def type(self) -> TestType:
        return self.config.test_type if self.config.test_type is not None else TestType.throughput

    def get_result(self) -> TestResult:
        return self.result

    def get_config(self) -> TestConfig:
        return self.config

    # ------------------------------------------------------------------
    # Shared helpers — receiver resolution and client/server defaulting
    # ------------------------------------------------------------------

    def resolve_receiver(self, network: 'INetwork',  # type: ignore
                         proto_info: IProtoInfo) -> Tuple[str, int]:
        """Resolve the receiver IP and port based on the protocol type.

        Proxy-style protocols (e.g. KCP, QUIC) forward traffic through a
        tunnel on the **client** host.  All other protocols (direct, TUN,
        BATS …) send traffic towards the **server** host.

        Returns:
            ``(receiver_ip, receiver_port)``
        """
        hosts = network.get_hosts()
        client = hosts[self.config.client_host]
        server = hosts[self.config.server_host]
        proto_name = proto_info.get_protocol_name().upper()

        if proto_name in PROXY_PROTOCOLS:
            tun_ip = proto_info.get_tun_ip(network, self.config.client_host)
            receiver_ip = tun_ip if tun_ip else client.IP()
        else:
            tun_ip = proto_info.get_tun_ip(network, self.config.server_host)
            receiver_ip = tun_ip if tun_ip else server.IP()

        receiver_port = proto_info.get_forward_port()
        return receiver_ip, receiver_port

    def _default_client_server(self, network: 'INetwork') -> None:  # type: ignore
        """Set ``client_host`` to 0 and ``server_host`` to last host when unset."""
        if self.config.client_host is None or self.config.server_host is None:
            hosts = network.get_hosts()
            if hosts:
                self.config.client_host = 0
                self.config.server_host = len(hosts) - 1

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def __validate_host_config(self, network: 'INetwork') -> bool:  # type: ignore
        hosts = network.get_hosts()
        if hosts is None:
            return True
        hosts_num = len(hosts)
        if self.config.client_host is not None and self.config.server_host is not None:
            if self.config.client_host >= hosts_num or self.config.server_host >= hosts_num:
                logging.error("Invalid client or server host id, client: %d, server: %d",
                              self.config.client_host, self.config.server_host)
                return False
        return True


# ======================================================================
# Test-suite registry — allows adding a new tool without editing runner.py
# ======================================================================

# Maps a tool name to its registration metadata.
#   'class'          — the ITestSuite subclass
#   'match'          — 'exact' (default) or 'contains'
#   'from_tool_dict' — optional classmethod for YAML→TestConfig mapping
_TEST_SUITE_REGISTRY: Dict[str, dict] = {}


def register_test_suite(name: str, match: str = 'exact',
                        test_type: Optional[TestType] = None):
    """Class decorator that registers an ``ITestSuite`` subclass.

    Args:
        name:      The tool name used in YAML (e.g. ``'bats_iperf'``).
        match:     ``'exact'`` requires ``tool['name'] == name``.
                   ``'contains'`` requires ``name in tool['name']``.
        test_type: If provided, ``TestConfig.test_type`` is set automatically
                   by the default ``from_tool_dict``.

    Example::

        @register_test_suite('ping', test_type=TestType.latency)
        class PingTest(ITestSuite):
            ...
    """
    def decorator(cls: Type['ITestSuite']):
        _TEST_SUITE_REGISTRY[name] = {
            'class': cls,
            'match': match,
            'test_type': test_type,
        }
        return cls
    return decorator


def get_test_suite_registry() -> Dict[str, dict]:
    """Return a *read-only copy* of the current registry (for testing)."""
    return dict(_TEST_SUITE_REGISTRY)


def load_test_suite_from_registry(
        tool: dict, test_name: str,
        root_path: str = DEFAULT_ROOT_PATH) -> Optional['ITestSuite']:
    """Look up *tool* in the registry and return an ``ITestSuite`` instance.

    Resolution order:

    1. Exact match on ``tool['name']``.
    2. First ``'contains'`` match where ``key in tool['name']``.
    3. Returns ``None`` (caller should fall back to ``RegularTest``).
    """
    name = tool['name']

    # 1. exact match
    if name in _TEST_SUITE_REGISTRY:
        entry = _TEST_SUITE_REGISTRY[name]
        cls = entry['class']
        if hasattr(cls, 'from_tool_dict'):
            return cls.from_tool_dict(tool, test_name, root_path)

    # 2. contains match
    for key, entry in _TEST_SUITE_REGISTRY.items():
        if entry['match'] == 'contains' and key in name:
            cls = entry['class']
            if hasattr(cls, 'from_tool_dict'):
                return cls.from_tool_dict(tool, test_name, root_path)

    return None
